/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as Explore_topicsRouteImport } from './routes/explore_topics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTopicIndexRouteImport } from './routes/t.$topic.index'
import { Route as TTopicCreatepostIndexRouteImport } from './routes/t.$topic.createpost.index'
import { Route as TTopicPPostIndexRouteImport } from './routes/t.$topic.p.$post.index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const Explore_topicsRoute = Explore_topicsRouteImport.update({
  id: '/explore_topics',
  path: '/explore_topics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicIndexRoute = TTopicIndexRouteImport.update({
  id: '/t/$topic/',
  path: '/t/$topic/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicCreatepostIndexRoute = TTopicCreatepostIndexRouteImport.update({
  id: '/t/$topic/createpost/',
  path: '/t/$topic/createpost/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicPPostIndexRoute = TTopicPPostIndexRouteImport.update({
  id: '/t/$topic/p/$post/',
  path: '/t/$topic/p/$post/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore_topics': typeof Explore_topicsRoute
  '/sign-up': typeof SignUpRoute
  '/t/$topic/': typeof TTopicIndexRoute
  '/t/$topic/createpost/': typeof TTopicCreatepostIndexRoute
  '/t/$topic/p/$post/': typeof TTopicPPostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore_topics': typeof Explore_topicsRoute
  '/sign-up': typeof SignUpRoute
  '/t/$topic': typeof TTopicIndexRoute
  '/t/$topic/createpost': typeof TTopicCreatepostIndexRoute
  '/t/$topic/p/$post': typeof TTopicPPostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore_topics': typeof Explore_topicsRoute
  '/sign-up': typeof SignUpRoute
  '/t/$topic/': typeof TTopicIndexRoute
  '/t/$topic/createpost/': typeof TTopicCreatepostIndexRoute
  '/t/$topic/p/$post/': typeof TTopicPPostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore_topics'
    | '/sign-up'
    | '/t/$topic/'
    | '/t/$topic/createpost/'
    | '/t/$topic/p/$post/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore_topics'
    | '/sign-up'
    | '/t/$topic'
    | '/t/$topic/createpost'
    | '/t/$topic/p/$post'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore_topics'
    | '/sign-up'
    | '/t/$topic/'
    | '/t/$topic/createpost/'
    | '/t/$topic/p/$post/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Explore_topicsRoute: typeof Explore_topicsRoute
  SignUpRoute: typeof SignUpRoute
  TTopicIndexRoute: typeof TTopicIndexRoute
  TTopicCreatepostIndexRoute: typeof TTopicCreatepostIndexRoute
  TTopicPPostIndexRoute: typeof TTopicPPostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore_topics': {
      id: '/explore_topics'
      path: '/explore_topics'
      fullPath: '/explore_topics'
      preLoaderRoute: typeof Explore_topicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/': {
      id: '/t/$topic/'
      path: '/t/$topic'
      fullPath: '/t/$topic/'
      preLoaderRoute: typeof TTopicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/createpost/': {
      id: '/t/$topic/createpost/'
      path: '/t/$topic/createpost'
      fullPath: '/t/$topic/createpost/'
      preLoaderRoute: typeof TTopicCreatepostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/p/$post/': {
      id: '/t/$topic/p/$post/'
      path: '/t/$topic/p/$post'
      fullPath: '/t/$topic/p/$post/'
      preLoaderRoute: typeof TTopicPPostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Explore_topicsRoute: Explore_topicsRoute,
  SignUpRoute: SignUpRoute,
  TTopicIndexRoute: TTopicIndexRoute,
  TTopicCreatepostIndexRoute: TTopicCreatepostIndexRoute,
  TTopicPPostIndexRoute: TTopicPPostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
